### ISSUE TITLE
API transaction.input decoder

### ISSUE THREAD

**Issue by flefevre** [JacqMT/web3j-maven-example#1]
Hello
any idea if this version is now able to generate Smart contract application binary interface encoders/decoders for transaction.getInput()
I would appreciate our help.
Francois

**Comment by JacqMT** [comment]
No, I'm afraid I don't know. I haven't kept as up to date with the Blockchain or web3j movement as I would have liked, so this has kind of just become a reference project in case it's useful to anyone getting started. The original has perhaps been updated though? https://github.com/web3j/web3j

Hopefully that helps, otherwise maybe Conor can help.

Thanks for taking a look, and good luck!
